# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b8c529fd64d6a60a6a7e0af26f36c88772deb555c552a72d98b3fdf7b425ed78b420165045633e2d80ee1deb831595a7e852f18c59ace4fbba5d4838387dc29

test:
  secret_key_base: 23796f8885ada77fa6513366ceb6d29b2ef1c960b39728409dfa8fba584cde151ad89d06b047f44a780b78c4bfc0657c4d50f329afe704a797e368f3255824d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
